Milestone 5
verissimohenry/calculator-react pull request #5
Opened 2021-08-27 16:54 UTC by verissimohenry

the last task is to tie the calculations module with the components and to add the interaction to the buttons.

2021-08-27 19:15 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @verissimohenry**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] Please make sure to add division by zero error. Right now when I divide by zero nothing happens. Please make sure to fix that,

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-08-27 21:20 UTC, taiwo2 requested changes
# STATUS: CHANGES REQUIRED  ♻️ 
@verissimohenry well-done on this milestone, what commendable efforts on trying to implement the suggested changes, however, changes are required
Please make sure to display  `division by zero error`. when divide by zero.

### once specific changes are made kindly request for review

2021-08-28 14:08 UTC, bellom requested changes
## Hi @verissimohenry :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

2021-08-28 14:08 UTC, bellom commented on src/logic/operate.js
> +/* eslint-disable no-undef */
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

2021-08-28 14:08 UTC, bellom commented on src/logic/operate.js
> +      else calculation = previousNum / currentNum;
const used in here seem undefined 🤔 

Hint: [Microverse operate.js template](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/code-samples/operate.js)

![image](https://user-images.githubusercontent.com/31897434/131220542-8889fab1-0964-4abd-a679-a195cdb612d4.png)


With the above example, kindly fix the `eslint` and add division by zero error message.

2021-08-28 15:35 UTC, rindrajosia requested changes
Hi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [x] Your APP crashed when I do a division by 0. Please fix it:
![1](https://user-images.githubusercontent.com/58552748/131222897-dc18c735-f16b-40aa-9694-36a8263bb0f8.png)

- [x] Your APP return ` Not valid operation` when I use +/- and *.
- [ ] I got an error related to propType when I do an operation.
![2](https://user-images.githubusercontent.com/58552748/131223051-dbf28c17-8f6f-4505-9ade-0a8017e91279.gif)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [x] Make sure that your APP is styled based on Milestone 3.
- [x] Files not related to the project should not be committed and added to .gitignore (e.g. .vscode) 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-28 16:38 UTC, christianotieno approved these changes
Hi @verissimohenry, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

2021-08-28 20:04 UTC, merged